### ISSUE TITLE
Difference with 1.0.5

### ISSUE THREAD

**Issue by geckotdf** [ian-travers/nfsu-server#6]
Hi!
What the diference between this version and the 1.0.5 of Harpy?

Thanks!

**Comment by ian-travers** [comment]
The main goal was to implement REP points system and statistics like in the original game.

**Comment by geckotdf** [comment]
I see,
So I can replace the 1.0.5 with this version with a new rusers.dat and will have the REP Points system working?

**Comment by ian-travers** [comment]
You can try. Then you can check whether it worked or not.
